### PR TITLE
Try building for windows??

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by BoPeng** [comment]
As I commented [here](https://github.com/conda-forge/staged-recipes/pull/9348#discussion_r321967292), there are two problems with running `bash_kernel` under windows. Removing `noarch: python` could solve the first bug (https://github.com/conda-forge/staged-recipes/issues/9465) but `bash_kernel` will still not work with `m2_bash` due to the second one (https://github.com/takluyver/bash_kernel/issues/96).

@blink1073 or @takluyver : Do you see a quick fix to https://github.com/takluyver/bash_kernel/issues/96? I tried to use `pexpect.popen_spawn` but could not get `expect()` to read a new line.

**Comment by blink1073** [comment]
Here is what we did for the Calysto Bash kernel to get it working on Windows.  I'm not sure how far apart the code bases are now.  https://github.com/Calysto/metakernel/blob/f16faf5ff4410ef0c52dff45c64249c72db52197/metakernel/replwrap.py#L299

**Comment by BoPeng** [comment]
Ohmm, I also did the `child.echo = echo` hack, perhaps I was not far from getting `bash_kernel` work. 

Is https://github.com/Calysto/calysto_bash supposed to work under windows? If so, perhaps we can add it to `conda_forge` first and then back-port the windows fix to `bash_kernel`.

**Comment by blink1073** [comment]
Yes, I have used Calysto bash on Windows with Git Bash.

**Comment by BoPeng** [comment]
@blink1073 Let us add `calysta_bash` to conda-forge first https://github.com/conda-forge/staged-recipes/pull/9476

**Comment by hmaarrfk** [comment]
hmm, seems like the pexepect issue is a real one that can't be easily overcome.

You might have to contact people at conda-forge core to take down the noarch package....
https://conda-forge.org/docs/orga/guidelines.html#fix-broken-packages

I don't like bugging the core team though.

**Comment by hmaarrfk** [comment]
The hard dependency on bash makes this package not installable on windows anyway. That said, it seems like the build number wasn't bumped, so the added dependency didn't make its way to conda-forge.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by BoPeng** [comment]
https://github.com/takluyver/bash_kernel/issues/96#issuecomment-529335773

@takluyver has stated clearly that he does not want to support windows, so we should stop this effort.

**Pull request merged**
