### PR TITLE
bump build number for additional bash dependency

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

- Build 0 didn't include the hard dependency on bash, necessary for this package to work.

https://anaconda.org/conda-forge/bash_kernel/files

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Sorry I’m confused. Is there still an issue with the package?

**Comment by hmaarrfk** [comment]
Yea, rerendering failed so I folded this back to the other PR I had

**Pull request closed without merging**
